name: Rust

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cargo install cargo-all-features
    - name: Build
      run: cargo build-all-features

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clippy Check
        run: cargo clippy --all-targets --all-features -- -D clippy::all -D warnings

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test
